Add database
okbascreed/java-filmorate pull request #7
Opened 2023-03-07 16:06 UTC by okbascreed

Приветствую!
Прошу прощения, что так задержался!

2023-03-08 18:13 UTC, db-exp requested changes

2023-03-08 18:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(@Qualifier("userDbStorage") UserStorage userStorage, UserService userService) {
UserStorage нужно использовать из UserService, чтобы не смешивать слои

2023-03-08 18:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +
лишняя строка

2023-03-08 18:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +    private MpaService mpaService;
на уровне storage лучше вызывать другие storage

2023-03-08 18:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +                        mpaService.getMpaById(rs.getInt("rating_id")),
правильней сделать запрос с join'ом

2023-03-08 18:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmStorage filmStorage;
FilmStorage нужно использовать из FilmService, чтобы не смешивать слои

2023-03-08 18:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                new HashSet<>(likeStorage.getLikes(rs.getInt("id"))),
лучше достать через join'ы

2023-03-08 18:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    new HashSet<>(likeStorage.getLikes(filmRows.getInt("id"))),
лучше достать через join

2023-03-09 20:15 UTC, okbascreed commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +
Спасибо, поправил!

2023-03-09 20:15 UTC, okbascreed commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +    private MpaService mpaService;
Спасибо, поправил!

2023-03-09 20:15 UTC, okbascreed commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +                        mpaService.getMpaById(rs.getInt("rating_id")),
Спасибо, поправил!

2023-03-09 20:15 UTC, okbascreed commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmStorage filmStorage;
Спасибо, поправил!

2023-03-09 20:16 UTC, okbascreed commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                new HashSet<>(likeStorage.getLikes(rs.getInt("id"))),
Спасибо, поправил!

2023-03-09 20:16 UTC, closed without merging

2023-03-09 21:22 UTC, db-exp reviewed
Все хорошо